{{- if .Values.envs.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envs.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end -}}