annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.3.2
dependencies:
  - condition: zookeeper.enabled
    name: zookeeper
    repository: file://../zookeeper
    version: 11.1.2
  - name: common
    repository: file://../common
    tags:
      - bitnami-common
    version: 2.2.3
description: Apache Kafka is a distributed streaming platform designed to build real-time pipelines and can be used as a message broker or as a replacement for a log aggregation solution for big data applications.
home: https://github.com/bitnami/charts/tree/main/bitnami/kafka
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
keywords:
  - kafka
  - zookeeper
  - streaming
  - producer
  - consumer
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: kafka
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/kafka
  - https://kafka.apache.org/
version: 20.0.6
